version: "3"

services:
  rcds:
    build: .
    command: ["rcds", "deploy"]
    volumes:
      - ./:/challenge/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:/var/run/docker.sock
    networks:
      - rctf

networks:
  rctf:
    name: rctf_rctf
